FROM mongo

EXPOSE 27017

# Linux:

# BUILD: sudo docker build -t marketplace_mongo .
# RUN: sudo docker run -p 6000:27017 -it --name marketplace_mongo_container -d marketplace_mongo

# Windows:

# BUILD: docker build -t marketplace_mongo .
# RUN: docker run -p 6000:27017 -it --name marketplace_mongo_container -d marketplace_mongo